name = "Mint Chocolate Chip"
author = "Chev"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c651c5f49832f9ead5423e97147e0d1fedb476f75c051188f0dda50af0673823"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
