name = "Mint Chocolate Chip"
author = "Chev"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7686b02ce945fab1ba2786f7508f5b3b98e4d7c0fdc6f99700123bb8646d9dc2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
