name = "Mint Chocolate Chip"
author = "Chev"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "303e2a11c0b70e55dd9b6a5baa44d54c0084c72555c2d8de2e96d4a96ca10ce9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
