name = "Mint Chocolate Chip"
author = "Chev"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29ca7146ee2fbf11b3156e3632d59089ea76cdcb9d877e8bc24a168c0dc901f3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
