name = "Mint Chocolate Chip"
author = "Chev"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cea368580c124f3d53dfd240d82b7aaa8a11cbf424b02eb7aa7ac5016eb6f41b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
