name = "Mint Chocolate Chip"
author = "Chev"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3313786d5c306b4f730c1bc3dff5a87cd9ef7191465b874313caef5ddda0c770"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
